FROM golang:1.22.2

# Создаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . .

# Сборка Go-приложения
RUN go mod tidy
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sysstat sudo net-tools iproute2 tcpdump \
    && rm -rf /var/lib/apt/lists/*

RUN go build -o server /cmd/server/server.go

# Определяем команду для запуска приложения
CMD ["./server"]