// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.1
// source: system_stats_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SystemStatsRequest) Reset() {
	*x = SystemStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsRequest) ProtoMessage() {}

func (x *SystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{0}
}

type CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMode   float64 `protobuf:"fixed64,1,opt,name=user_mode,json=userMode,proto3" json:"user_mode,omitempty"`
	SystemMode float64 `protobuf:"fixed64,2,opt,name=system_mode,json=systemMode,proto3" json:"system_mode,omitempty"`
	Idle       float64 `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *CPU) Reset() {
	*x = CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *CPU) GetUserMode() float64 {
	if x != nil {
		return x.UserMode
	}
	return 0
}

func (x *CPU) GetSystemMode() float64 {
	if x != nil {
		return x.SystemMode
	}
	return 0
}

func (x *CPU) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mounted string `protobuf:"bytes,1,opt,name=mounted,proto3" json:"mounted,omitempty"`
	Use     string `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Iuse    string `protobuf:"bytes,3,opt,name=iuse,proto3" json:"iuse,omitempty"`
}

func (x *Disk) Reset() {
	*x = Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *Disk) GetMounted() string {
	if x != nil {
		return x.Mounted
	}
	return ""
}

func (x *Disk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Disk) GetIuse() string {
	if x != nil {
		return x.Iuse
	}
	return ""
}

type IoStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskDevice string  `protobuf:"bytes,1,opt,name=disk_device,json=diskDevice,proto3" json:"disk_device,omitempty"`
	Tps        float64 `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
	KbRead     float64 `protobuf:"fixed64,3,opt,name=kb_read,json=kbRead,proto3" json:"kb_read,omitempty"`
	KbWrtn     float64 `protobuf:"fixed64,4,opt,name=kb_wrtn,json=kbWrtn,proto3" json:"kb_wrtn,omitempty"`
}

func (x *IoStat) Reset() {
	*x = IoStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoStat) ProtoMessage() {}

func (x *IoStat) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoStat.ProtoReflect.Descriptor instead.
func (*IoStat) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{3}
}

func (x *IoStat) GetDiskDevice() string {
	if x != nil {
		return x.DiskDevice
	}
	return ""
}

func (x *IoStat) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *IoStat) GetKbRead() float64 {
	if x != nil {
		return x.KbRead
	}
	return 0
}

func (x *IoStat) GetKbWrtn() float64 {
	if x != nil {
		return x.KbWrtn
	}
	return 0
}

type NetStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Program  string `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	Pid      int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port     int32  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	State    string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *NetStat) Reset() {
	*x = NetStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetStat) ProtoMessage() {}

func (x *NetStat) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetStat.ProtoReflect.Descriptor instead.
func (*NetStat) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{4}
}

func (x *NetStat) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *NetStat) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetStat) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *NetStat) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetStat) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetStat) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TCPStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All      int32 `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Estab    int32 `protobuf:"varint,2,opt,name=estab,proto3" json:"estab,omitempty"`
	Closed   int32 `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	Orphaned int32 `protobuf:"varint,4,opt,name=orphaned,proto3" json:"orphaned,omitempty"`
	Timewait int32 `protobuf:"varint,5,opt,name=timewait,proto3" json:"timewait,omitempty"`
}

func (x *TCPStat) Reset() {
	*x = TCPStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCPStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPStat) ProtoMessage() {}

func (x *TCPStat) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPStat.ProtoReflect.Descriptor instead.
func (*TCPStat) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{5}
}

func (x *TCPStat) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *TCPStat) GetEstab() int32 {
	if x != nil {
		return x.Estab
	}
	return 0
}

func (x *TCPStat) GetClosed() int32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

func (x *TCPStat) GetOrphaned() int32 {
	if x != nil {
		return x.Orphaned
	}
	return 0
}

func (x *TCPStat) GetTimewait() int32 {
	if x != nil {
		return x.Timewait
	}
	return 0
}

type SystemStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadAverage float64    `protobuf:"fixed64,1,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	Cpu         *CPU       `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Disks       []*Disk    `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	Iostat      []*IoStat  `protobuf:"bytes,4,rep,name=iostat,proto3" json:"iostat,omitempty"`
	Netstat     []*NetStat `protobuf:"bytes,5,rep,name=netstat,proto3" json:"netstat,omitempty"`
	Tcpstat     *TCPStat   `protobuf:"bytes,6,opt,name=tcpstat,proto3" json:"tcpstat,omitempty"`
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_stats_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_stats_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_system_stats_service_proto_rawDescGZIP(), []int{6}
}

func (x *SystemStatsResponse) GetLoadAverage() float64 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *SystemStatsResponse) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemStatsResponse) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemStatsResponse) GetIostat() []*IoStat {
	if x != nil {
		return x.Iostat
	}
	return nil
}

func (x *SystemStatsResponse) GetNetstat() []*NetStat {
	if x != nil {
		return x.Netstat
	}
	return nil
}

func (x *SystemStatsResponse) GetTcpstat() *TCPStat {
	if x != nil {
		return x.Tcpstat
	}
	return nil
}

var File_system_stats_service_proto protoreflect.FileDescriptor

var file_system_stats_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x57, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x04, 0x44, 0x69, 0x73,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x75, 0x73,
	0x65, 0x22, 0x6d, 0x0a, 0x06, 0x49, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x69, 0x73, 0x6b, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x69, 0x73, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x6b, 0x62, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x6b, 0x62, 0x52, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x62, 0x5f, 0x77, 0x72,
	0x74, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6b, 0x62, 0x57, 0x72, 0x74, 0x6e,
	0x22, 0x8f, 0x01, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x54, 0x43, 0x50, 0x53, 0x74, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x73, 0x74, 0x61, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x65, 0x73, 0x74, 0x61, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x72, 0x70, 0x68, 0x61, 0x6e, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6f, 0x72, 0x70, 0x68, 0x61, 0x6e, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x77, 0x61, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x77, 0x61, 0x69, 0x74, 0x22, 0x97, 0x02, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x12, 0x23, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x43, 0x50,
	0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x28, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73,
	0x12, 0x2c, 0x0a, 0x06, 0x69, 0x6f, 0x73, 0x74, 0x61, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x49, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x52, 0x06, 0x69, 0x6f, 0x73, 0x74, 0x61, 0x74, 0x12, 0x2f,
	0x0a, 0x07, 0x6e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x4e,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x12,
	0x2f, 0x0a, 0x07, 0x74, 0x63, 0x70, 0x73, 0x74, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x54, 0x43, 0x50, 0x53, 0x74, 0x61, 0x74, 0x52, 0x07, 0x74, 0x63, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x32, 0x70, 0x0a, 0x12, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_system_stats_service_proto_rawDescOnce sync.Once
	file_system_stats_service_proto_rawDescData = file_system_stats_service_proto_rawDesc
)

func file_system_stats_service_proto_rawDescGZIP() []byte {
	file_system_stats_service_proto_rawDescOnce.Do(func() {
		file_system_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_system_stats_service_proto_rawDescData)
	})
	return file_system_stats_service_proto_rawDescData
}

var file_system_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_system_stats_service_proto_goTypes = []interface{}{
	(*SystemStatsRequest)(nil),  // 0: system_stats.SystemStatsRequest
	(*CPU)(nil),                 // 1: system_stats.CPU
	(*Disk)(nil),                // 2: system_stats.Disk
	(*IoStat)(nil),              // 3: system_stats.IoStat
	(*NetStat)(nil),             // 4: system_stats.NetStat
	(*TCPStat)(nil),             // 5: system_stats.TCPStat
	(*SystemStatsResponse)(nil), // 6: system_stats.SystemStatsResponse
}
var file_system_stats_service_proto_depIdxs = []int32{
	1, // 0: system_stats.SystemStatsResponse.cpu:type_name -> system_stats.CPU
	2, // 1: system_stats.SystemStatsResponse.disks:type_name -> system_stats.Disk
	3, // 2: system_stats.SystemStatsResponse.iostat:type_name -> system_stats.IoStat
	4, // 3: system_stats.SystemStatsResponse.netstat:type_name -> system_stats.NetStat
	5, // 4: system_stats.SystemStatsResponse.tcpstat:type_name -> system_stats.TCPStat
	0, // 5: system_stats.SystemStatsService.StreamSystemStats:input_type -> system_stats.SystemStatsRequest
	6, // 6: system_stats.SystemStatsService.StreamSystemStats:output_type -> system_stats.SystemStatsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_system_stats_service_proto_init() }
func file_system_stats_service_proto_init() {
	if File_system_stats_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_system_stats_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IoStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCPStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_stats_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_system_stats_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_stats_service_proto_goTypes,
		DependencyIndexes: file_system_stats_service_proto_depIdxs,
		MessageInfos:      file_system_stats_service_proto_msgTypes,
	}.Build()
	File_system_stats_service_proto = out.File
	file_system_stats_service_proto_rawDesc = nil
	file_system_stats_service_proto_goTypes = nil
	file_system_stats_service_proto_depIdxs = nil
}
